require 'shoehorn/connection'
require 'shoehorn/bill'
require 'shoehorn/business_card'
require 'shoehorn/category'
require 'shoehorn/image'
require 'shoehorn/other_document'
require 'shoehorn/receipt'
